### ISSUE TITLE
Scena nie jest centrowana [ubuntu, Qt 5.5, gcc 4.8.4]

### ISSUE THREAD

**Issue by PawelBednarz** [Michalaq/ChromosomeVisualizer#1]
Cząsteczka pojawia się w odległej części sceny. Pod ubuntu nie działa mechanizm centrowania widoku na cząsteczce (jeśli taki jest zaimplementowany).

**Comment by Michalaq** [comment]
Naprawione + obrót jest wokół zaznaczenia lub punktu (0,0).

**Comment by PawelBednarz** [comment]
Problem cały czas występuje.
