### ISSUE TITLE
Za mała rozdzielczość paska do przewijania klatek [ubuntu 14.04, Qt 5.5, gcc 4.8.4]

### ISSUE THREAD

**Issue by PawelBednarz** [Michalaq/ChromosomeVisualizer#11]
Podczas klikania na pasek przewijania klatek: po kliknięciu da się nim przewijać tylko co 10 klatek, mimo, że celuję kursorem pomiędzy te 10 klatek (przewijanie poprzez przeciąganie wskaźnika działa precyzyjnie)

**Comment by Michalaq** [comment]
Dodany drugi pasek: dolny pasek to wybór zakresu symulacji, który chcemy oglądać, zaś górny pasek służy do wyboru konkretnej klatki z tego zakresu. + dodatkowo można wpisać klatkę / użyć strzałek przy numerze klatki do dokładniejszego wyboru.
