### ISSUE TITLE
Regulacja wielkości panelu z wizualizowaną funkcją

### ISSUE THREAD

**Issue by PawelBednarz** [Michalaq/ChromosomeVisualizer#13]
Powinno dać się zmieniać wielkość panelu z rysowaną funkcją - teraz zabiera ok. 1/3 ekranu i nic nie da się z tym zrobić; do tego powinno się ten panel dać zminimalizować

**Comment by Michalaq** [comment]
Gotowe, choć niewykluczone, że dalej będziemy nad tym pracować: obecnie domyślnie wykres jest zsunięty do dołu, by go pokazać trzeba złapać i rozciągnąć te okienko.
