### ISSUE TITLE
Dziwny efekt wizualny podczas zmiany wielkości kulek

### ISSUE THREAD

**Issue by PawelBednarz** [Michalaq/ChromosomeVisualizer#14]
Połączenia pomiędzy cząsteczkami nie odświeżają się od razu po zmianie rozmiaru kulek, tylko dopiero po ponownym kliknięciu na scenę (podczas gdy samym kulkom rozmiar jest zmieniany od razu - daje to dość dziwny efekt widoczny na screenshocie
![screenshot from 2016-01-27 13 52 45](https://cloud.githubusercontent.com/assets/1370593/12613999/73762a4c-c4fd-11e5-94a1-641893ee1309.png)
)

**Comment by Michalaq** [comment]
Naprawione.
