### ISSUE TITLE
Preview range?

### ISSUE THREAD

**Issue by PawelBednarz** [Michalaq/ChromosomeVisualizer#33]
Co robi kliknięcie na animation->play mode? Wydaje się, że nic... Co miało robić?

**Comment by bartekz450** [comment]
Animation->Play mode zmienia sposób odtwarzania animacji. Jeśli jest zaznaczone "Preview range", wtedy odtwarzanie zatrzymuje się w momencie, kiedy czas dobiegnie do końca przedziału zaznaczonego na dolnym suwaku. Wyjątkiem jest sytuacja, gdy prawy koniec dolnego suwaka jest na ostatniej ramce. Wtedy domyślnym zachowaniem jest wczytanie następnych ramek i przedłużenie przedziału. Opcje Simple/Cycle mówią o tym, co ma się stać po zakończeniu odtwarzania. Simple zatrzymuje animację, zaś Cycle odtwarza ją od początku.
