### ISSUE TITLE
Czarna ramka przy select [ubuntu 14.04, Qt 5.5, gcc 4.8.4]

### ISSUE THREAD

**Issue by PawelBednarz** [Michalaq/ChromosomeVisualizer#9]
U mnie zaznaczanie odbywa się poprzez rozciągnięcie czarnego prostokąta. Wygląda to kiepsko, bo zasłania znajdujące się pod spodem atomy.
![czarna_ramka](https://cloud.githubusercontent.com/assets/1370593/12613798/3deb8c24-c4fc-11e5-9246-9c6487c30156.png)

**Comment by Michalaq** [comment]
Naprawione.
